"""add scoped_document_id to query_logs

Revision ID: 52ce5e7bd576
Revises: fa3cad496904
Create Date: 2026-09-11 16:52:01.035070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ce5e7bd576'
down_revision: Union[str, None] = 'fa3cad496904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('scoped_document_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_query_logs_scoped_document_id'), 'query_logs', ['scoped_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_logs_scoped_document_id'), table_name='query_logs')
    op.drop_column('query_logs', 'scoped_document_id')
    # ### end Alembic commands ###
