"""add query_logs table

Revision ID: d1a25efb49ed
Revises: 57b69b1b6011
Create Date: 2026-09-09 10:46:17.002205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a25efb49ed'
down_revision: Union[str, None] = '57b69b1b6011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('rewritten_query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('retrieved_dense', sa.JSON(), nullable=True),
    sa.Column('retrieved_sparse', sa.JSON(), nullable=True),
    sa.Column('fused_candidates', sa.JSON(), nullable=True),
    sa.Column('reranked_chunks', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('faithfulness_score', sa.Float(), nullable=True),
    sa.Column('context_precision_score', sa.Float(), nullable=True),
    sa.Column('answer_relevance_score', sa.Float(), nullable=True),
    sa.Column('eval_passed', sa.Boolean(), nullable=True),
    sa.Column('eval_detail', sa.JSON(), nullable=True),
    sa.Column('latency_retrieval_ms', sa.Integer(), nullable=False),
    sa.Column('latency_rerank_ms', sa.Integer(), nullable=False),
    sa.Column('latency_llm_ms', sa.Integer(), nullable=False),
    sa.Column('latency_eval_ms', sa.Integer(), nullable=False),
    sa.Column('latency_total_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_created_at'), 'query_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_created_at'), table_name='query_logs')
    op.drop_table('query_logs')
    # ### end Alembic commands ###
